In [20]:
import pandas as pd
import numpy as np
l=[18,20,10,12,15]
b=[20,20,10,15,17]

df=pd.DataFrame({"length":l,"breadth":b})
print(df)

df["prize"] = [3000000,4000000,2000000,2500000,1500000]
print(df)
df["prize"] = np.where(df["prize"]>=3000000, "high", np.where(df["prize"]>=2000000,"med","low"))
df

   length  breadth
0      18       20
1      20       20
2      10       10
3      12       15
4      15       17
   length  breadth    prize
0      18       20  3000000
1      20       20  4000000
2      10       10  2000000
3      12       15  2500000
4      15       17  1500000

   length  breadth prize
0      18       20  high
1      20       20  high
2      10       10   med
3      12       15   med
4      15       17   low

In [21]:
df["area"]=df["length"]*df["breadth"]
df["area1"]=df["area"]+20
print(df)

   length  breadth prize  area  area1
0      18       20  high   360    380
1      20       20  high   400    420
2      10       10   med   100    120
3      12       15   med   180    200
4      15       17   low   255    275

In [6]:
df=pd.DataFrame({"rollno":[1,2,3,4,5], "city" :["a","b","c","b","a"]})
df
df1 = pd.get_dummies(data=df) 
df1

   rollno  city_a  city_b  city_c
0       1    True   False   False
1       2   False    True   False
2       3   False   False    True
3       4   False    True   False
4       5    True   False   False

In [7]:
df1 = pd.get_dummies(data=df, drop_first=True) # if a col is useless then you should remove it so there is less load on ml model while training....
df1

   rollno  city_b  city_c
0       1   False   False
1       2    True   False
2       3   False    True
3       4    True   False
4       5   False   False

In [2]:
from sklearn.model_selection import train_test_split
import pandas as pd

df= pd.read_csv("car data.csv")
df["age"] = 2026 - df["Year"]
print(df.info()
      )
x = df[["age","Present_Price","Kms_Driven","Fuel_Type","Transmission"]]
y= df["Selling_Price"]
x=pd.get_dummies(data=x , drop_first=True)
print(x)

x_train, x_test, y_train, y_test = train_test_split(x,y,train_size=0.2, random_state=41)
print(x_train.shape)
print(y_train.shape)
print(x_test.shape)
print(y_test.shape)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 301 entries, 0 to 300
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Car_Name       301 non-null    object
 1   Year           301 non-null    int64
 2   Selling_Price  301 non-null    float64
 3   Present_Price  301 non-null    float64
 4   Kms_Driven     301 non-null    int64
 5   Fuel_Type      301 non-null    object
 6   Seller_Type    301 non-null    object
 7   Transmission   301 non-null    object
 8   Owner          301 non-null    int64
 9   age            301 non-null    int64
dtypes: float64(2), int64(4), object(4)
memory usage: 23.6+ KB
None
     age  Present_Price  Kms_Driven  Fuel_Type_Diesel  Fuel_Type_Petrol  \
0     12           5.59       27000             False              True
1     13           9.54       43000              True             False
2      9           9.85        6900             False              True
3     15           4.15        5200             False              True
4     12           6.87       42450              True             False
..   ...            ...         ...               ...               ...
296   10          11.60       33988              True             False
297   11           5.90       60000             False              True
298   17          11.00       87934             False              True
299    9          12.50        9000              True             False
300   10           5.90        5464             False              True

     Transmission_Manual
0                   True
1                   True
2                   True
3                   True
4                   True
..                   ...
296                 True
297                 True
298                 True
299                 True
300                 True

[301 rows x 6 columns]
(60, 6)
(60,)
(241, 6)
(241,)